Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision "shell", path: "../packer/install-desktop.sh"
  config.vm.provision "shell", path: "../packer/install-devtools.sh"
end